# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/edenthread/Documents/CM_Company_Disk_Tool_Design.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(700, 400)
        MainWindow.setMinimumSize(QtCore.QSize(700, 400))
        MainWindow.setMaximumSize(QtCore.QSize(700, 400))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(220, 10, 461, 351))
        self.tabWidget.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.tabWidget.setFocusPolicy(QtCore.Qt.FocusPolicy.TabFocus)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.console_tab = QtWidgets.QWidget()
        self.console_tab.setStyleSheet("")
        self.console_tab.setObjectName("console_tab")
        self.output = QtWidgets.QTextBrowser(self.console_tab)
        self.output.setGeometry(QtCore.QRect(0, 0, 461, 331))
        self.output.setObjectName("output")
        self.tabWidget.addTab(self.console_tab, "")
        self.info_tab = QtWidgets.QWidget()
        self.info_tab.setObjectName("info_tab")
        self.output_2 = QtWidgets.QTextBrowser(self.info_tab)
        self.output_2.setGeometry(QtCore.QRect(0, 0, 461, 331))
        self.output_2.setObjectName("output_2")
        self.tabWidget.addTab(self.info_tab, "")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setGeometry(QtCore.QRect(10, 20, 201, 331))
        self.splitter.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.splitter.setObjectName("splitter")
        self.disk_list_button = QtWidgets.QPushButton(self.splitter)
        self.disk_list_button.setObjectName("disk_list_button")
        self.disk_list_button.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.unmount_disk_button = QtWidgets.QPushButton(self.splitter)
        self.unmount_disk_button.setObjectName("unmount_disk_button")
        self.unmount_disk_button.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.mount_disk_button = QtWidgets.QPushButton(self.splitter)
        self.mount_disk_button.setObjectName("mount_disk_button")
        self.mount_disk_button.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.mount_alldisk_button = QtWidgets.QPushButton(self.splitter)
        self.mount_alldisk_button.setObjectName("mount_alldisk_button")
        self.mount_alldisk_button.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CM Company Disk Tool"))
        self.output.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\" bgcolor=\"#000000\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ffffff;\">[13:49:45]: CM Company Disk Tool running on v1.0.0.</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.console_tab), _translate("MainWindow", "Console"))
        self.output_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">CM Company Disk Tool developped by @LudovicAns.</p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.info_tab), _translate("MainWindow", "Informations"))
        self.disk_list_button.setText(_translate("MainWindow", "Liste des disques"))
        self.unmount_disk_button.setText(_translate("MainWindow", "Démonter des disques"))
        self.mount_disk_button.setText(_translate("MainWindow", "Monter des disques"))
        self.mount_alldisk_button.setText(_translate("MainWindow", "Monter tout les disques"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
